# A sample Guardfile
# More info at https://github.com/guard/guard#readme

config = {
  :host => '0.0.0.0',
  :port => '35729',
}

guard 'livereload' do
  watch(%r{components/.+\.(css|js|html)})
  # watch(%r{app/views/.+\.(erb|haml|slim)$})
  # watch(%r{app/helpers/.+\.rb})
  # watch(%r{public/.+\.(css|js|html)})
  # watch(%r{config/locales/.+\.yml})
  # Rails Assets Pipeline
  # watch(%r{(app|vendor)(/assets/\w+/(.+\.(css|js|html))).*}) { |m| "/assets/#{m[3]}" }
end

guard 'webrick'
